### ISSUE TITLE
runtume error 

### ISSUE THREAD

**Issue by jisu5619** [udacity/CarND-LaneLines-P1#106]
----> 8 white_clip = clip1.fl_image(process_image) 

Name error. 

I guess this line have a problem "clip1 = VideoFileClip("test_videos/solidWhiteRight.mp4")"
it was look like not finding solidWhileRight.mp4.

what is the solution about this complie error . not found solidWhiteRight.mp4

Thanks

**Comment by UAnjali** [comment]
Though we are a little late to respond, You can visit [this](https://knowledge.udacity.com/questions/57658) thread for the issue you are facing. Still, if this couldn't resolve the issue, we encourage such _user-specific_ issues to be raised on the Knowledge hub so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
